
package py.com.ceamso.ws.csj.autenticacion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Autenticacion", targetNamespace = "http://www.csj.gov.py/", wsdlLocation = "http://www.csj.gov.py/appseguridad/seguridad/sistema/autenticacion.asmx?wsdl")
public class Autenticacion
    extends Service
{

    private final static URL AUTENTICACION_WSDL_LOCATION;
    private final static WebServiceException AUTENTICACION_EXCEPTION;
    private final static QName AUTENTICACION_QNAME = new QName("http://www.csj.gov.py/", "Autenticacion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.csj.gov.py/appseguridad/seguridad/sistema/autenticacion.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTENTICACION_WSDL_LOCATION = url;
        AUTENTICACION_EXCEPTION = e;
    }

    public Autenticacion() {
        super(__getWsdlLocation(), AUTENTICACION_QNAME);
    }

    public Autenticacion(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTENTICACION_QNAME, features);
    }

    public Autenticacion(URL wsdlLocation) {
        super(wsdlLocation, AUTENTICACION_QNAME);
    }

    public Autenticacion(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTENTICACION_QNAME, features);
    }

    public Autenticacion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Autenticacion(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AutenticacionSoap
     */
    @WebEndpoint(name = "AutenticacionSoap")
    public AutenticacionSoap getAutenticacionSoap() {
        return super.getPort(new QName("http://www.csj.gov.py/", "AutenticacionSoap"), AutenticacionSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutenticacionSoap
     */
    @WebEndpoint(name = "AutenticacionSoap")
    public AutenticacionSoap getAutenticacionSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.csj.gov.py/", "AutenticacionSoap"), AutenticacionSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTENTICACION_EXCEPTION!= null) {
            throw AUTENTICACION_EXCEPTION;
        }
        return AUTENTICACION_WSDL_LOCATION;
    }

}
