
package py.com.ceamso.ws.csj.autenticacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutenticacionSoap", targetNamespace = "http://www.csj.gov.py/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutenticacionSoap {


    /**
     * Autenticación de Usuario
     * 
     * @param aplicacion
     * @param usuario
     * @param rol
     * @param clave
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.CControlAutenticacion
     */
    @WebMethod(operationName = "Autenticar", action = "http://www.csj.gov.py/Autenticar")
    @WebResult(name = "AutenticarResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "Autenticar", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.Autenticar")
    @ResponseWrapper(localName = "AutenticarResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.AutenticarResponse")
    public CControlAutenticacion autenticar(
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        String usuario,
        @WebParam(name = "clave", targetNamespace = "http://www.csj.gov.py/")
        String clave,
        @WebParam(name = "aplicacion", targetNamespace = "http://www.csj.gov.py/")
        int aplicacion,
        @WebParam(name = "rol", targetNamespace = "http://www.csj.gov.py/")
        int rol);

    /**
     * Cambio de Contraseña
     * 
     * @param renuevaClave
     * @param claveActual
     * @param usuarioSolicitante
     * @param nuevaClave
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.TEstadoCambioClave
     */
    @WebMethod(operationName = "CambiarClave", action = "http://www.csj.gov.py/CambiarClave")
    @WebResult(name = "CambiarClaveResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "CambiarClave", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.CambiarClave")
    @ResponseWrapper(localName = "CambiarClaveResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.CambiarClaveResponse")
    public TEstadoCambioClave cambiarClave(
        @WebParam(name = "usuarioSolicitante", targetNamespace = "http://www.csj.gov.py/")
        CControlAutenticacion usuarioSolicitante,
        @WebParam(name = "claveActual", targetNamespace = "http://www.csj.gov.py/")
        String claveActual,
        @WebParam(name = "nuevaClave", targetNamespace = "http://www.csj.gov.py/")
        String nuevaClave,
        @WebParam(name = "renuevaClave", targetNamespace = "http://www.csj.gov.py/")
        String renuevaClave);

    /**
     * Lista las aplicaciones relacioadas a un usuario dado
     * 
     * @param usuario
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerAplicacionesPorUsuarioResponse.ObtenerAplicacionesPorUsuarioResult
     */
    @WebMethod(operationName = "ObtenerAplicacionesPorUsuario", action = "http://www.csj.gov.py/ObtenerAplicacionesPorUsuario")
    @WebResult(name = "ObtenerAplicacionesPorUsuarioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerAplicacionesPorUsuario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerAplicacionesPorUsuario")
    @ResponseWrapper(localName = "ObtenerAplicacionesPorUsuarioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerAplicacionesPorUsuarioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerAplicacionesPorUsuarioResponse.ObtenerAplicacionesPorUsuarioResult obtenerAplicacionesPorUsuario(
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        int usuario);

    /**
     * Lista las aplicaciones relacioadas a un usuario dado
     * 
     * @param usuario
     * @param rol
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerAplicacionesPorRolUsuarioResponse.ObtenerAplicacionesPorRolUsuarioResult
     */
    @WebMethod(operationName = "ObtenerAplicacionesPorRolUsuario", action = "http://www.csj.gov.py/ObtenerAplicacionesPorRolUsuario")
    @WebResult(name = "ObtenerAplicacionesPorRolUsuarioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerAplicacionesPorRolUsuario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerAplicacionesPorRolUsuario")
    @ResponseWrapper(localName = "ObtenerAplicacionesPorRolUsuarioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerAplicacionesPorRolUsuarioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerAplicacionesPorRolUsuarioResponse.ObtenerAplicacionesPorRolUsuarioResult obtenerAplicacionesPorRolUsuario(
        @WebParam(name = "rol", targetNamespace = "http://www.csj.gov.py/")
        int rol,
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        int usuario);

    /**
     * Lista las aplicaciones relacioadas a un usuario dado
     * 
     * @param circunscripcion
     * @param usuario
     * @param rol
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerAplicacionesPorUsuarioRolCircunscrpcionResponse.ObtenerAplicacionesPorUsuarioRolCircunscrpcionResult
     */
    @WebMethod(operationName = "ObtenerAplicacionesPorUsuarioRolCircunscrpcion", action = "http://www.csj.gov.py/ObtenerAplicacionesPorUsuarioRolCircunscrpcion")
    @WebResult(name = "ObtenerAplicacionesPorUsuarioRolCircunscrpcionResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerAplicacionesPorUsuarioRolCircunscrpcion", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerAplicacionesPorUsuarioRolCircunscrpcion")
    @ResponseWrapper(localName = "ObtenerAplicacionesPorUsuarioRolCircunscrpcionResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerAplicacionesPorUsuarioRolCircunscrpcionResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerAplicacionesPorUsuarioRolCircunscrpcionResponse.ObtenerAplicacionesPorUsuarioRolCircunscrpcionResult obtenerAplicacionesPorUsuarioRolCircunscrpcion(
        @WebParam(name = "rol", targetNamespace = "http://www.csj.gov.py/")
        int rol,
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        int usuario,
        @WebParam(name = "circunscripcion", targetNamespace = "http://www.csj.gov.py/")
        int circunscripcion);

    /**
     * Lista las opciones del Menú  de un Formulario, por Usuario, con sus atributos
     * 
     * @param formulario
     * @param usuario
     * @param rol
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerAtributosMenuFormularioResponse.ObtenerAtributosMenuFormularioResult
     */
    @WebMethod(operationName = "ObtenerAtributosMenuFormulario", action = "http://www.csj.gov.py/ObtenerAtributosMenuFormulario")
    @WebResult(name = "ObtenerAtributosMenuFormularioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerAtributosMenuFormulario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerAtributosMenuFormulario")
    @ResponseWrapper(localName = "ObtenerAtributosMenuFormularioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerAtributosMenuFormularioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerAtributosMenuFormularioResponse.ObtenerAtributosMenuFormularioResult obtenerAtributosMenuFormulario(
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        int usuario,
        @WebParam(name = "formulario", targetNamespace = "http://www.csj.gov.py/")
        int formulario,
        @WebParam(name = "rol", targetNamespace = "http://www.csj.gov.py/")
        int rol);

    /**
     * Lista los campos de un Formulario, por Usuario, con sus atributos
     * 
     * @param formulario
     * @param usuario
     * @param rol
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerAtributosCampoFormularioResponse.ObtenerAtributosCampoFormularioResult
     */
    @WebMethod(operationName = "ObtenerAtributosCampoFormulario", action = "http://www.csj.gov.py/ObtenerAtributosCampoFormulario")
    @WebResult(name = "ObtenerAtributosCampoFormularioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerAtributosCampoFormulario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerAtributosCampoFormulario")
    @ResponseWrapper(localName = "ObtenerAtributosCampoFormularioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerAtributosCampoFormularioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerAtributosCampoFormularioResponse.ObtenerAtributosCampoFormularioResult obtenerAtributosCampoFormulario(
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        int usuario,
        @WebParam(name = "formulario", targetNamespace = "http://www.csj.gov.py/")
        int formulario,
        @WebParam(name = "rol", targetNamespace = "http://www.csj.gov.py/")
        int rol);

    /**
     * Lista los objetos de un Formulario, por Usuario, con sus atributos
     * 
     * @param formulario
     * @param usuario
     * @param rol
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerAtributosObjetoFormularioResponse.ObtenerAtributosObjetoFormularioResult
     */
    @WebMethod(operationName = "ObtenerAtributosObjetoFormulario", action = "http://www.csj.gov.py/ObtenerAtributosObjetoFormulario")
    @WebResult(name = "ObtenerAtributosObjetoFormularioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerAtributosObjetoFormulario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerAtributosObjetoFormulario")
    @ResponseWrapper(localName = "ObtenerAtributosObjetoFormularioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerAtributosObjetoFormularioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerAtributosObjetoFormularioResponse.ObtenerAtributosObjetoFormularioResult obtenerAtributosObjetoFormulario(
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        int usuario,
        @WebParam(name = "formulario", targetNamespace = "http://www.csj.gov.py/")
        int formulario,
        @WebParam(name = "rol", targetNamespace = "http://www.csj.gov.py/")
        int rol);

    /**
     * Lista los roles de una aplicación
     * 
     * @param aplicacion
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerRolesPorAplicacionResponse.ObtenerRolesPorAplicacionResult
     */
    @WebMethod(operationName = "ObtenerRolesPorAplicacion", action = "http://www.csj.gov.py/ObtenerRolesPorAplicacion")
    @WebResult(name = "ObtenerRolesPorAplicacionResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerRolesPorAplicacion", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerRolesPorAplicacion")
    @ResponseWrapper(localName = "ObtenerRolesPorAplicacionResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerRolesPorAplicacionResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerRolesPorAplicacionResponse.ObtenerRolesPorAplicacionResult obtenerRolesPorAplicacion(
        @WebParam(name = "aplicacion", targetNamespace = "http://www.csj.gov.py/")
        int aplicacion);

    /**
     * Lista los usuarios de una aplicación
     * 
     * @param aplicacion
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerUsuariosPorAplicacionResponse.ObtenerUsuariosPorAplicacionResult
     */
    @WebMethod(operationName = "ObtenerUsuariosPorAplicacion", action = "http://www.csj.gov.py/ObtenerUsuariosPorAplicacion")
    @WebResult(name = "ObtenerUsuariosPorAplicacionResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerUsuariosPorAplicacion", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerUsuariosPorAplicacion")
    @ResponseWrapper(localName = "ObtenerUsuariosPorAplicacionResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerUsuariosPorAplicacionResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerUsuariosPorAplicacionResponse.ObtenerUsuariosPorAplicacionResult obtenerUsuariosPorAplicacion(
        @WebParam(name = "aplicacion", targetNamespace = "http://www.csj.gov.py/")
        int aplicacion);

    /**
     * Lista de usuarios por Rol de una Aplicación dada
     * 
     * @param aplicacion
     * @param rol
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerUsuariosPorRolAplicacionResponse.ObtenerUsuariosPorRolAplicacionResult
     */
    @WebMethod(operationName = "ObtenerUsuariosPorRolAplicacion", action = "http://www.csj.gov.py/ObtenerUsuariosPorRolAplicacion")
    @WebResult(name = "ObtenerUsuariosPorRolAplicacionResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerUsuariosPorRolAplicacion", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerUsuariosPorRolAplicacion")
    @ResponseWrapper(localName = "ObtenerUsuariosPorRolAplicacionResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerUsuariosPorRolAplicacionResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerUsuariosPorRolAplicacionResponse.ObtenerUsuariosPorRolAplicacionResult obtenerUsuariosPorRolAplicacion(
        @WebParam(name = "aplicacion", targetNamespace = "http://www.csj.gov.py/")
        int aplicacion,
        @WebParam(name = "rol", targetNamespace = "http://www.csj.gov.py/")
        int rol);

    /**
     * Lista los roles de una aplicación por Usuario
     * 
     * @param aplicacion
     * @param usuario
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerRolesPorUsuarioResponse.ObtenerRolesPorUsuarioResult
     */
    @WebMethod(operationName = "ObtenerRolesPorUsuario", action = "http://www.csj.gov.py/ObtenerRolesPorUsuario")
    @WebResult(name = "ObtenerRolesPorUsuarioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerRolesPorUsuario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerRolesPorUsuario")
    @ResponseWrapper(localName = "ObtenerRolesPorUsuarioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerRolesPorUsuarioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerRolesPorUsuarioResponse.ObtenerRolesPorUsuarioResult obtenerRolesPorUsuario(
        @WebParam(name = "aplicacion", targetNamespace = "http://www.csj.gov.py/")
        int aplicacion,
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        String usuario);

    /**
     * Lista los roles por Usuario
     * 
     * @param usuario
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerRolesUsuarioResponse.ObtenerRolesUsuarioResult
     */
    @WebMethod(operationName = "ObtenerRolesUsuario", action = "http://www.csj.gov.py/ObtenerRolesUsuario")
    @WebResult(name = "ObtenerRolesUsuarioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerRolesUsuario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerRolesUsuario")
    @ResponseWrapper(localName = "ObtenerRolesUsuarioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerRolesUsuarioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerRolesUsuarioResponse.ObtenerRolesUsuarioResult obtenerRolesUsuario(
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        int usuario);

    /**
     * Retorna la clase con sus atributos
     * 
     * @param siglas
     * @param codigoRol
     * @param codigoAplicacion
     * @param codigoUsuario
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "ObtenerClaseAtributoAplicacion", action = "http://www.csj.gov.py/ObtenerClaseAtributoAplicacion")
    @WebResult(name = "ObtenerClaseAtributoAplicacionResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerClaseAtributoAplicacion", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerClaseAtributoAplicacion")
    @ResponseWrapper(localName = "ObtenerClaseAtributoAplicacionResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerClaseAtributoAplicacionResponse")
    public Object obtenerClaseAtributoAplicacion(
        @WebParam(name = "CodigoUsuario", targetNamespace = "http://www.csj.gov.py/")
        int codigoUsuario,
        @WebParam(name = "CodigoRol", targetNamespace = "http://www.csj.gov.py/")
        int codigoRol,
        @WebParam(name = "CodigoAplicacion", targetNamespace = "http://www.csj.gov.py/")
        int codigoAplicacion,
        @WebParam(name = "SIGLAS", targetNamespace = "http://www.csj.gov.py/")
        String siglas);

    /**
     * Retona la lista de formularios
     * 
     * @param codigoRol
     * @param codigoAplicacion
     * @param codigoUsuario
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerFormulariosDeAplicacionPorUsuarioResponse.ObtenerFormulariosDeAplicacionPorUsuarioResult
     */
    @WebMethod(operationName = "ObtenerFormulariosDeAplicacionPorUsuario", action = "http://www.csj.gov.py/ObtenerFormulariosDeAplicacionPorUsuario")
    @WebResult(name = "ObtenerFormulariosDeAplicacionPorUsuarioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerFormulariosDeAplicacionPorUsuario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerFormulariosDeAplicacionPorUsuario")
    @ResponseWrapper(localName = "ObtenerFormulariosDeAplicacionPorUsuarioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerFormulariosDeAplicacionPorUsuarioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerFormulariosDeAplicacionPorUsuarioResponse.ObtenerFormulariosDeAplicacionPorUsuarioResult obtenerFormulariosDeAplicacionPorUsuario(
        @WebParam(name = "CodigoAplicacion", targetNamespace = "http://www.csj.gov.py/")
        int codigoAplicacion,
        @WebParam(name = "CodigoUsuario", targetNamespace = "http://www.csj.gov.py/")
        int codigoUsuario,
        @WebParam(name = "CodigoRol", targetNamespace = "http://www.csj.gov.py/")
        int codigoRol);

    /**
     * Retona la lista de menu de un formulario a partir de un usuario y su rol
     * 
     * @param codigoFormulario
     * @param codigoRol
     * @param codigoUsuario
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerMenuFormularioPorUsuarioResponse.ObtenerMenuFormularioPorUsuarioResult
     */
    @WebMethod(operationName = "ObtenerMenuFormularioPorUsuario", action = "http://www.csj.gov.py/ObtenerMenuFormularioPorUsuario")
    @WebResult(name = "ObtenerMenuFormularioPorUsuarioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerMenuFormularioPorUsuario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerMenuFormularioPorUsuario")
    @ResponseWrapper(localName = "ObtenerMenuFormularioPorUsuarioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerMenuFormularioPorUsuarioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerMenuFormularioPorUsuarioResponse.ObtenerMenuFormularioPorUsuarioResult obtenerMenuFormularioPorUsuario(
        @WebParam(name = "CodigoFormulario", targetNamespace = "http://www.csj.gov.py/")
        int codigoFormulario,
        @WebParam(name = "CodigoUsuario", targetNamespace = "http://www.csj.gov.py/")
        int codigoUsuario,
        @WebParam(name = "CodigoRol", targetNamespace = "http://www.csj.gov.py/")
        int codigoRol);

    /**
     * Retona la lista de campos de un formulario a partir de un usuario y su rol
     * 
     * @param codigoFormulario
     * @param codigoRol
     * @param codigoUsuario
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerCamposFormularioPorUsuarioResponse.ObtenerCamposFormularioPorUsuarioResult
     */
    @WebMethod(operationName = "ObtenerCamposFormularioPorUsuario", action = "http://www.csj.gov.py/ObtenerCamposFormularioPorUsuario")
    @WebResult(name = "ObtenerCamposFormularioPorUsuarioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerCamposFormularioPorUsuario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerCamposFormularioPorUsuario")
    @ResponseWrapper(localName = "ObtenerCamposFormularioPorUsuarioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerCamposFormularioPorUsuarioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerCamposFormularioPorUsuarioResponse.ObtenerCamposFormularioPorUsuarioResult obtenerCamposFormularioPorUsuario(
        @WebParam(name = "CodigoFormulario", targetNamespace = "http://www.csj.gov.py/")
        int codigoFormulario,
        @WebParam(name = "CodigoUsuario", targetNamespace = "http://www.csj.gov.py/")
        int codigoUsuario,
        @WebParam(name = "CodigoRol", targetNamespace = "http://www.csj.gov.py/")
        int codigoRol);

    /**
     * Retona la lista de objetos de un formulario a partir de un usuario y su rol
     * 
     * @param codigoFormulario
     * @param codigoRol
     * @param codigoUsuario
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerObjetosFormularioPorUsuarioResponse.ObtenerObjetosFormularioPorUsuarioResult
     */
    @WebMethod(operationName = "ObtenerObjetosFormularioPorUsuario", action = "http://www.csj.gov.py/ObtenerObjetosFormularioPorUsuario")
    @WebResult(name = "ObtenerObjetosFormularioPorUsuarioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerObjetosFormularioPorUsuario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerObjetosFormularioPorUsuario")
    @ResponseWrapper(localName = "ObtenerObjetosFormularioPorUsuarioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerObjetosFormularioPorUsuarioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerObjetosFormularioPorUsuarioResponse.ObtenerObjetosFormularioPorUsuarioResult obtenerObjetosFormularioPorUsuario(
        @WebParam(name = "codigoFormulario", targetNamespace = "http://www.csj.gov.py/")
        int codigoFormulario,
        @WebParam(name = "codigoUsuario", targetNamespace = "http://www.csj.gov.py/")
        int codigoUsuario,
        @WebParam(name = "codigoRol", targetNamespace = "http://www.csj.gov.py/")
        int codigoRol);

    /**
     * Lista las circunscripciones de una aplicación determinada
     * 
     * @param aplicacion
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesPorAplicacionResponse.ObtenerCircunscripcionesPorAplicacionResult
     */
    @WebMethod(operationName = "ObtenerCircunscripcionesPorAplicacion", action = "http://www.csj.gov.py/ObtenerCircunscripcionesPorAplicacion")
    @WebResult(name = "ObtenerCircunscripcionesPorAplicacionResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerCircunscripcionesPorAplicacion", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesPorAplicacion")
    @ResponseWrapper(localName = "ObtenerCircunscripcionesPorAplicacionResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesPorAplicacionResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesPorAplicacionResponse.ObtenerCircunscripcionesPorAplicacionResult obtenerCircunscripcionesPorAplicacion(
        @WebParam(name = "aplicacion", targetNamespace = "http://www.csj.gov.py/")
        int aplicacion);

    /**
     * Registro de circunscripción de una aplicación y rol determinado
     * 
     * @param aplicacion
     * @param circunscripcion
     * @param usuario
     * @param rol
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.CCircunscripcion
     */
    @WebMethod(operationName = "ObtenerCircunscripcionPorAplicacionRol", action = "http://www.csj.gov.py/ObtenerCircunscripcionPorAplicacionRol")
    @WebResult(name = "ObtenerCircunscripcionPorAplicacionRolResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerCircunscripcionPorAplicacionRol", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionPorAplicacionRol")
    @ResponseWrapper(localName = "ObtenerCircunscripcionPorAplicacionRolResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionPorAplicacionRolResponse")
    public CCircunscripcion obtenerCircunscripcionPorAplicacionRol(
        @WebParam(name = "circunscripcion", targetNamespace = "http://www.csj.gov.py/")
        int circunscripcion,
        @WebParam(name = "aplicacion", targetNamespace = "http://www.csj.gov.py/")
        int aplicacion,
        @WebParam(name = "rol", targetNamespace = "http://www.csj.gov.py/")
        int rol,
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        int usuario);

    /**
     * Lista las Circunscripciones por Usuario y Rol
     * 
     * @param usuario
     * @param rol
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesPorUsuarioRolResponse.ObtenerCircunscripcionesPorUsuarioRolResult
     */
    @WebMethod(operationName = "ObtenerCircunscripcionesPorUsuarioRol", action = "http://www.csj.gov.py/ObtenerCircunscripcionesPorUsuarioRol")
    @WebResult(name = "ObtenerCircunscripcionesPorUsuarioRolResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerCircunscripcionesPorUsuarioRol", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesPorUsuarioRol")
    @ResponseWrapper(localName = "ObtenerCircunscripcionesPorUsuarioRolResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesPorUsuarioRolResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesPorUsuarioRolResponse.ObtenerCircunscripcionesPorUsuarioRolResult obtenerCircunscripcionesPorUsuarioRol(
        @WebParam(name = "rol", targetNamespace = "http://www.csj.gov.py/")
        int rol,
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        int usuario);

    /**
     * Lista las Circunscripciones de una aplicación por Usuario
     * 
     * @param aplicacion
     * @param usuario
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesAplicacionPorUsuarioResponse.ObtenerCircunscripcionesAplicacionPorUsuarioResult
     */
    @WebMethod(operationName = "ObtenerCircunscripcionesAplicacionPorUsuario", action = "http://www.csj.gov.py/ObtenerCircunscripcionesAplicacionPorUsuario")
    @WebResult(name = "ObtenerCircunscripcionesAplicacionPorUsuarioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerCircunscripcionesAplicacionPorUsuario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesAplicacionPorUsuario")
    @ResponseWrapper(localName = "ObtenerCircunscripcionesAplicacionPorUsuarioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesAplicacionPorUsuarioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesAplicacionPorUsuarioResponse.ObtenerCircunscripcionesAplicacionPorUsuarioResult obtenerCircunscripcionesAplicacionPorUsuario(
        @WebParam(name = "aplicacion", targetNamespace = "http://www.csj.gov.py/")
        int aplicacion,
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        int usuario);

    /**
     * Lista las Circunscripciones de una aplicación
     * 
     * @param aplicacion
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesAplicacionResponse.ObtenerCircunscripcionesAplicacionResult
     */
    @WebMethod(operationName = "ObtenerCircunscripcionesAplicacion", action = "http://www.csj.gov.py/ObtenerCircunscripcionesAplicacion")
    @WebResult(name = "ObtenerCircunscripcionesAplicacionResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerCircunscripcionesAplicacion", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesAplicacion")
    @ResponseWrapper(localName = "ObtenerCircunscripcionesAplicacionResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesAplicacionResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerCircunscripcionesAplicacionResponse.ObtenerCircunscripcionesAplicacionResult obtenerCircunscripcionesAplicacion(
        @WebParam(name = "aplicacion", targetNamespace = "http://www.csj.gov.py/")
        int aplicacion);

    /**
     * Lista los Roles de un Usuario relacionada a una Circunscripcion
     * 
     * @param aplicacion
     * @param circunscripcion
     * @param usuario
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.ObtenerRolesCircunscripcionesAplicacionPorUsuarioResponse.ObtenerRolesCircunscripcionesAplicacionPorUsuarioResult
     */
    @WebMethod(operationName = "ObtenerRolesCircunscripcionesAplicacionPorUsuario", action = "http://www.csj.gov.py/ObtenerRolesCircunscripcionesAplicacionPorUsuario")
    @WebResult(name = "ObtenerRolesCircunscripcionesAplicacionPorUsuarioResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "ObtenerRolesCircunscripcionesAplicacionPorUsuario", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerRolesCircunscripcionesAplicacionPorUsuario")
    @ResponseWrapper(localName = "ObtenerRolesCircunscripcionesAplicacionPorUsuarioResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.ObtenerRolesCircunscripcionesAplicacionPorUsuarioResponse")
    public py.com.ceamso.ws.csj.autenticacion.ObtenerRolesCircunscripcionesAplicacionPorUsuarioResponse.ObtenerRolesCircunscripcionesAplicacionPorUsuarioResult obtenerRolesCircunscripcionesAplicacionPorUsuario(
        @WebParam(name = "aplicacion", targetNamespace = "http://www.csj.gov.py/")
        int aplicacion,
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        String usuario,
        @WebParam(name = "circunscripcion", targetNamespace = "http://www.csj.gov.py/")
        int circunscripcion);

    /**
     * Generar un nuevo Ticket
     * 
     * @param circunscripcion
     * @param usuario
     * @param json
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GenerarTicket", action = "http://www.csj.gov.py/GenerarTicket")
    @WebResult(name = "GenerarTicketResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "GenerarTicket", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.GenerarTicket")
    @ResponseWrapper(localName = "GenerarTicketResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.GenerarTicketResponse")
    public boolean generarTicket(
        @WebParam(name = "key", targetNamespace = "http://www.csj.gov.py/")
        String key,
        @WebParam(name = "json", targetNamespace = "http://www.csj.gov.py/")
        String json,
        @WebParam(name = "usuario", targetNamespace = "http://www.csj.gov.py/")
        int usuario,
        @WebParam(name = "circunscripcion", targetNamespace = "http://www.csj.gov.py/")
        int circunscripcion);

    /**
     * Retorna los datos de un ticket
     * 
     * @param key
     * @return
     *     returns py.com.ceamso.ws.csj.autenticacion.Ticket
     */
    @WebMethod(operationName = "DatosTicket", action = "http://www.csj.gov.py/DatosTicket")
    @WebResult(name = "DatosTicketResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "DatosTicket", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.DatosTicket")
    @ResponseWrapper(localName = "DatosTicketResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.DatosTicketResponse")
    public Ticket datosTicket(
        @WebParam(name = "key", targetNamespace = "http://www.csj.gov.py/")
        String key);

    /**
     * Retorna los datos de un ticket
     * 
     * @param key
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "EliminaTicket", action = "http://www.csj.gov.py/EliminaTicket")
    @WebResult(name = "EliminaTicketResult", targetNamespace = "http://www.csj.gov.py/")
    @RequestWrapper(localName = "EliminaTicket", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.EliminaTicket")
    @ResponseWrapper(localName = "EliminaTicketResponse", targetNamespace = "http://www.csj.gov.py/", className = "py.com.ceamso.ws.csj.autenticacion.EliminaTicketResponse")
    public boolean eliminaTicket(
        @WebParam(name = "key", targetNamespace = "http://www.csj.gov.py/")
        String key);

}
